# Generated by Django 4.1.3 on 2022-11-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_section_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='terms',
            field=models.JSONField(default=dict),
        ),
    ]
