# Generated by Django 4.1.3 on 2022-11-24 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers_teacher_teacher_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_code',
        ),
    ]
