# Generated by Django 4.1.3 on 2022-11-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='feedback',
            field=models.TextField(),
        ),
    ]
