# Generated by Django 4.1.3 on 2022-12-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0003_grade_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigned_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='grade_type',
            field=models.CharField(blank=True, choices=[('A', 'Letter Grade'), ('N', 'Numerical Grade')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='term',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
